const fs = require("fs");
const path = require("path");
const util = require("util");
const execFile = util.promisify(require('child_process').execFile);

class N64LibDragonImageWriter {
    static mkspritePath = "/opt/libdragon/bin/mksprite";

    /* Converts an image file to a libdragon sprite in the /tmp directory
    returns the file path of the created sprite.
    */
    async writeLibdragonSprite(sourcePath, format) {
        const mkspriteArgs = [
            "--output", "/tmp",
            "--compress", "0",
            "--format", format,
            "--verbose",
            sourcePath
        ];
        
        await execFile(N64LibDragonImageWriter.mkspritePath, mkspriteArgs);

        // The filename is automatically generated by the mksprite program
        // TODO: handle case where filename already exists?
        const convertedSpriteFile = path.join("/tmp", path.basename(sourcePath, path.extname(sourcePath)) + ".sprite");

        if (!fs.existsSync(convertedSpriteFile)) {
            throw new Error(`Error converting image: ${sourcePath}`);
        }

        return convertedSpriteFile;
    }

    /** Writes a converted libdragon sprite to the file path. 
     * Note this assumes a single image slice in the image.
    */
    writeImageToPath(convertedSpriteFile, assetPath) {
        const assetFile = fs.openSync(assetPath, "w");
        this.writeImageToFile(convertedSpriteFile, assetFile);
        fs.closeSync(assetFile);
    }

    /** Writes a converted libdragon sprite to the open file descriptor. 
     * Note this assumes a single image slice in the image.
    */
    writeImageToFile(convertedSpriteFile, assetFile) {
        this.writeImageSlicesToFile([convertedSpriteFile], 1, 1, assetFile);
    }

    /** Writes converted libdragon sprite slices to a file at the given path */
    writeImageSlicesToPath(convertedSpriteFiles, hslices, vslices, assetPath) {
        const assetFile = fs.openSync(assetPath, "w");
        this.writeImageSlicesToFile(convertedSpriteFiles, hslices, vslices, assetFile);
        fs.closeSync(assetFile);
    }

    /** Writes converted libdragon sprite slices to the open file descriptor */
    writeImageSlicesToFile(convertedSpriteFiles, hslices, vslices, assetFile) {
        // write the image header. this needs to match fw64LibdragonImageInfo in libdragon_image.h
        const imageHeader = Buffer.alloc(4);
        imageHeader.writeUint16BE(hslices, 0);
        imageHeader.writeUint16BE(vslices, 2);
        fs.writeSync(assetFile, imageHeader);

        for (const convertedSpriteFile of convertedSpriteFiles) {
            this._writeImageFrameToFile(convertedSpriteFile, assetFile);
        }
    }

    _writeImageFrameToFile(convertedSpriteFile, assetFile) {
        // We want to append the uncompressed file size onto the front of the converted sprite.
        // This allows us to know how much data we need to read from the datasource when we load
        // this at runtime.
        // This should match fw64_libdragon_image_init_from_datasource logic in libdragon_image.c
        const convertedSpriteFileBuffer = fs.readFileSync(convertedSpriteFile);
        const sizeBuffer = Buffer.alloc(4);
        sizeBuffer.writeUInt32BE(convertedSpriteFileBuffer.length, 0);

        fs.writeSync(assetFile, sizeBuffer);
        fs.writeSync(assetFile, convertedSpriteFileBuffer);
    }
}

module.exports = N64LibDragonImageWriter
