#ifndef FW64_N64_CONTROLLER_BUTTON
#define FW64_N64_CONTROLLER_BUTTON

#include <nusys.h>

typedef enum {
    FW64_CONTROLLER_BUTTON_A = A_BUTTON,
    FW64_CONTROLLER_BUTTON_B = B_BUTTON,
    FW64_CONTROLLER_BUTTON_L = L_TRIG,
    FW64_CONTROLLER_BUTTON_R = R_TRIG,
    FW64_CONTROLLER_BUTTON_Z = Z_TRIG,
    FW64_CONTROLLER_BUTTON_START = START_BUTTON,
    FW64_CONTROLLER_BUTTON_C_UP = U_CBUTTONS,
    FW64_CONTROLLER_BUTTON_C_DOWN = D_CBUTTONS,
    FW64_CONTROLLER_BUTTON_C_LEFT = L_CBUTTONS,
    FW64_CONTROLLER_BUTTON_C_RIGHT = R_CBUTTONS,
    FW64_CONTROLLER_BUTTON_DPAD_UP = U_JPAD,
    FW64_CONTROLLER_BUTTON_DPAD_DOWN = D_JPAD,
    FW64_CONTROLLER_BUTTON_DPAD_LEFT = L_JPAD,
    FW64_CONTROLLER_BUTTON_DPAD_RIGHT = R_JPAD
} fw64ControllerButton;

#endif